version: "3.5"
services:

  mailman-sync:
    image: python:3.9-alpine
    command: "sh /opt/entrypoint.sh"
    volumes:
      - ./:/opt/:ro
      - ./last_updated.txt:/opt/last_updated.txt:rw
    networks:
      - webproxy
      - wannabe_internal
    restart: unless-stopped
  filestat:
    image: mdoubez/filestat_exporter
    command: -path.cwd /opt 'last_updated.txt'
    volumes:
      - ./last_updated.txt:/opt/last_updated.txt:ro
    ports:
      - "0.0.0.0:9943:9943"
    restart: unless-stopped

networks:
  webproxy:
    external: true
  wannabe_internal:
    external: true
